// This file is auto-generated by @hey-api/openapi-ts

export enum GenderEnum {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

export enum RoleEnum {
  ADMIN = 'ADMIN',
  SUB_ADMIN = 'SUB_ADMIN',
  USER = 'USER',
}

export enum AddressTypeEnum {
  HOME = 'HOME',
  OFFICE = 'OFFICE',
}

export enum DiscountTypeEnum {
  PERCENTAGE = 'PERCENTAGE',
  AMOUNT = 'AMOUNT',
}

/**
 * User's email
 */
export enum PaymentMethodEnum {
  CASH = 'CASH',
  CARD = 'CARD',
  STRIPE = 'STRIPE',
}

export enum OrderStatusEnum {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}
